// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Models;

namespace WebAPI.Migrations
{
    [DbContext(typeof(GibAdsDBContext))]
    partial class GibAdsDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAPI.Models.Order", b =>
            {
                b.Property<int>("id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("clientID")
                    .HasColumnType("nvarchar(10)");

                b.Property<string>("orderType")
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("oImagePath")
                    .HasColumnType("varchar(MAX)");

                b.Property<string>("oVideoPath")
                    .HasColumnType("varchar(MAX)");

                b.Property<string>("locationId")
                    .HasColumnType("nvarchar(10)");

                b.Property<string>("oComment")
                    .HasColumnType("varchar(MAX)");

                b.HasKey("id");

                b.ToTable("Orders");
            });


            modelBuilder.Entity("WebAPI.Models.Client", b =>
            {
                b.Property<int>("id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("clientName")
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("clientEmail")
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("dateOfJoining")
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("clientPhoto")
                    .HasColumnType("nvarchar(500)");


                b.HasKey("id");

                b.ToTable("Clients");
            });

#pragma warning restore 612, 618
        }
    }
}
